[project]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pixi_coacd"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
coacd = "python run_coacd.py "

[dependencies]
python = "==3.11"

[pypi-dependencies]
coacd = ">=1.0.5, <2"
trimesh = ">=4.5.3, <5"
